### ISSUE TITLE
Javelin Experiment Board について

### ISSUE THREAD

**Issue by keitakawamoto** [keitakawamoto/orangebomb.org#12]
概要や使い方など

**Comment by keitakawamoto** [comment]
## Javelin Experiment Board

通称 `ジャベリンボード`

- [](http://media.mediatemple.netdna-cdn.com/wp-content/uploads/2014/08/04-Javelin-Experiment-Board-large-opt.png)

**Comment by keitakawamoto** [comment]
## 関連記事

関係ありそうな記事・サイト一覧

- [Lean Startup Machine Tokyo December 2013](http://www.dnp.co.jp/cio/servicedesignlab/publicity-lsmt.html)
- [スタートアップロードマップ：リーンやグロースハックの概念を俯瞰して整理する](http://growthhack.vasily.jp/2015/01/startup-roadmap/)
- [「機能するデザイン」を考えるために、必要なこと。 UX Sketch Vol.4](http://mtl.recruit.co.jp/ux-sketch-vol4/)
- [Javelin Early Access](http://vip.javelin.com/)
- [amana tech night vol.3「達人たちから学ぶ。グロースハックとUI/UX」開催レポート≪前編≫](http://amanatech.org/amana-tech-night-vol-3_report-1)
- [TECH VALLEY#4グロースハックパーティ！ イベントレポ](http://suidenoti.hatenablog.com/entry/2015/04/27/214630)
- [なんとなく参加した講演会で、今までグロースハックは胡散臭いだけのバズワードと思っていたことを反省した](http://ojisan-a.hatenablog.com/entry/2015/04/15/233236)

**Comment by keitakawamoto** [comment]
## できるだけ翻訳してみた

Start here. Brainstorm with stickies, pull it over to the right to start your experiment.
付箋を使ってブレインストーミングをはじめよう。実験を始めるには右に引っ張ります。

Who is your customer? Be as specific as possible.
あなたの顧客は誰ですか？できるだけ具体的に。
制限時間５分

What is the problem? Phrase it from your customer’s perspective.
何が問題ですか？あなたの顧客の観点からフレーズを。
制限時間５分

Define the solution only after you have validated problem worth solving.
あなたは問題の価値解決を検証した後にのみソリューションを定義します。
制限時間５分

List the assumptions that must hold true, for your hypothesis to be true.
あなたの仮説が真であるためには、成立しなければならない前提条件をリストします。
制限時間１０分

Need help? Use these sentences to help construct your experiment.
助けが必要？あなたの実験を構築するために、これらの文を使用してください。

To form a Customer/Problem Hypothesis:
I believe my customer has a problem achieving this goal.
顧客/問題の仮説を形成するために：
私は私の顧客がこの目標を達成するため、問題があると考えています。

To form a Problem/Solution Hypothesis:
I believe this solution will result in quantifiable outcome.
問題/解決策の仮説を形成するために：
私は、このソリューションは、定量化可能な結果をもたらすであろうと考えています。

To form your Assumptions:
In order for hypothesis to be true, assumption needs to be true.
あなたの仮定を形成するには：
仮説が真であるために、仮定が真である必要があります。

To identify your Riskiest Assumption:
 The assumption with the least amount of data,and core to the viability of my hypothesis is…
あなたの最もリスクの高い仮定を同定するために：
私の仮説の生存能力に少なくともデータの量、およびコアとの仮定があります…

Determine how you will test it:
The least expensive way to test my assumption is…

あなたはそれをテストする方法を決定します：
私の仮説をテストするための最も安価な方法です…

Determine what success looks like:
I will run experiment with # of customers and expect a strong signal from # of customers.

成功がどのように見えるかを決定します:
私は顧客の＃で実験を実行して、顧客の＃から強い信号を期待しています。

Experiments
実験

Customer
顧客

Problem
問題

Solution
解決策

Riskiest Assumption
最もリスクの高い仮定

Method & Success Criterion
方法（やり方）＆達成基準

GET OUT OF THE BUILDING!
建物から抜け出します！

Result & Decision
結果＆決定

Learning
学習

**Comment by keitakawamoto** [comment]
### "リスク"とは？

“女性は全員料理をする” などのこと。
「本当に？例外なく全員料理するのか？」
などのリスクがある状態で検証なしにこのままプロダクトを進めると（間違っているかもしれないゆえに）失敗するかもしれない。検証してリスクをなくしていく必要がある。


```
レベル１〜５
レベル１が最もレベル高い（リスクが高い）
```

### 使い方

- 1.どんどん左側に書き出していく（全員で）
 - 想像できるもの “このプロダクトの顧客は誰か？問題は何か？解決策は何か？最も危険な仮説は何か”
- 2.下部のヒントは書き方サンプルなので気にしなくて良い
- 3.次に書き出したものの中から最もリスクの高いものを「１」のラインに移す。

サンプルでいうと

項目|サンプル内容
---|---
顧客|スタートアップの創業者
抱えている問題|UXのフィードバックを受けたくても受けられない（人脈も資金もツールもない）
解決策|なし（現時点では）
最もリスクの高い仮説（最も問題なのは）|信頼できる情報源がない(前述ゆえに)
方法・達成基準|ここまでの仮説を10人にインタビューして6人その通りだと答えたらこの仮説は正しいとする
ー|“取材を終えて、戻って検証しろ！”
結果&決定|結果を書く “その通りだった”
学習|これらの検証によって学んだこと “意外と〜〜だった”

- 4.満たしたら「１」そのまま残し「２」に移る
- 5.満たしていなければ（10人中6人み満たなかったら）「１」を他の仮説に差し替えて繰り返す

**Comment by shoyan** [comment]
壮大なイシューだ

**Comment by keitakawamoto** [comment]
## 使用するタイミング

- Q. すでに存在するもので行ったほうがよいのか、作り出す前に行ってもいいのか
- A. どちらでも利用可能

**Comment by keitakawamoto** [comment]
## 日本語翻訳向上版

ヒント部分は中途半端だけど。

@tkengo 協力ありがとう！

![default](https://cloud.githubusercontent.com/assets/1661325/13044802/8b32ee84-d413-11e5-893c-ba4f64ac6950.png)

**Comment by keitakawamoto** [comment]
# まとめ

@horaotoko が教えてくれた仮説検証ツール `Javelin Experiment Board` がよさそうだったのでまとめます。

![](https://camo.githubusercontent.com/1901b4b4d35afc7961dbc2146a1a5e43bb3df631/687474703a2f2f6d656469612e6d6564696174656d706c652e6e6574646e612d63646e2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031342f30382f30342d4a6176656c696e2d4578706572696d656e742d426f6172642d6c617267652d6f70742e706e67)

### 日本語訳ボード

作りました。

![](https://cloud.githubusercontent.com/assets/1661325/13044802/8b32ee84-d413-11e5-893c-ba4f64ac6950.png)

## ジャベリンボードとは？

**仮説検証ツール。**

アイデアの前提となるユーザーの課題が本当に存在するか、アプローチ方法が間違った前提に立脚していないかを検証する。
「誰の」「どんな問題を」「どうやって解決するか」と、それらの大前提となっている「仮説」をボード上にセットし、実際にオフィスの外に出て顧客と対話し、その仮説が本当に正しいのかを検証する。
http://growthhack.vasily.jp/2015/01/startup-roadmap/ より

『誰のどんな問題をどのように解決するかの理想を描き、描いた仮説が実在するか、
事前に検証できないかを検討し、現実とのギャップに学びながら軌道修正していく必要がある』
http://mtl.recruit.co.jp/ux-sketch-vol4/ より

## 使い方

![lsmt_3](https://git.pepabo.com/github-enterprise-assets/0000/0072/0007/6465/8533e654-d419-11e5-98cf-42cd0b1d40e7.jpg)![lsmt_5](https://git.pepabo.com/github-enterprise-assets/0000/0072/0007/6466/853494e6-d419-11e5-8cc2-f154d52abcb2.jpg)


- 1.どんどん左側に書き出していく（全員で）
 - 想像できるもの “このプロダクトの顧客は誰か？問題は何か？解決策は何か？最も問題なのは何か”
- 2.下部のヒントは書き方サンプルなので気にしなくて良い
- 3.次に書き出したものの中から最もリスクの高いものを「１」のラインに移す。

サンプルでいうと

項目|サンプル内容
---|---
顧客|スタートアップの創業者
抱えている問題|UXのフィードバックを受けたくても受けられない（人脈も資金もツールもない）
解決策|なし（現時点では）
最も問題なのは|信頼できる情報源がない(前述ゆえに)
方法・達成基準|ここまでの仮説を10人にインタビューして6人その通りだと答えたらこの仮説は正しいとする
結果&決定|結果を書く “その通りだった”
学習|これらの検証によって学んだこと “意外と〜〜だった”

- 4.満たしたら「１」そのまま残し「２」に移る
- 5.満たしていなければ（10人中6人み満たなかったら）「１」を他の仮説に差し替えて繰り返す

## "リスク"とは？

**“女性は全員料理をする” などの仮説。そのまま利用すると失敗する確率が高いもの。**
「本当に？例外なく全員料理するのか？」などのリスクがある状態で検証なしにこのままプロダクトを進めると（間違っているかもしれないゆえに）失敗するかもしれない。検証してリスクをなくしていく必要がある。

```
レベル１〜５
レベル１が最もレベル高い（リスクが高い）
```

## 使用するタイミング

- Q. すでに存在するもので行ったほうがよいのか、作り出す前に行ってもいいのか
- A. どちらでも利用可能

## 関連記事

関係ありそうな記事・サイト一覧

- [Lean Startup Machine Tokyo December 2013](http://www.dnp.co.jp/cio/servicedesignlab/publicity-lsmt.html)
- [スタートアップロードマップ：リーンやグロースハックの概念を俯瞰して整理する](http://growthhack.vasily.jp/2015/01/startup-roadmap/)
- [「機能するデザイン」を考えるために、必要なこと。 UX Sketch Vol.4](http://mtl.recruit.co.jp/ux-sketch-vol4/)
- [amana tech night vol.3「達人たちから学ぶ。グロースハックとUI/UX」開催レポート≪前編≫](http://amanatech.org/amana-tech-night-vol-3_report-1)
- [TECH VALLEY#4グロースハックパーティ！ イベントレポ](http://suidenoti.hatenablog.com/entry/2015/04/27/214630)
- [なんとなく参加した講演会で、今までグロースハックは胡散臭いだけのバズワードと思っていたことを反省した](http://ojisan-a.hatenablog.com/entry/2015/04/15/233236)

[Javelin](http://vip.javelin.com/)は現在アーリーアクセスの人しか使えないようになっている模様。
