### ISSUE TITLE
Electronについて / 学ぶために簡単なものを作る

### ISSUE THREAD

**Issue by keitakawamoto** [keitakawamoto/orangebomb.org#16]
http://electron.atom.io/
公式ドキュメント：http://electron.atom.io/docs/

![image](https://cloud.githubusercontent.com/assets/1661325/13450968/0068a4d4-e07e-11e5-9aa9-e6db31882756.png)

**Comment by keitakawamoto** [comment]
## 何を作る？

![](https://d13yacurqjgara.cloudfront.net/users/236204/screenshots/2557566/cowboy.gif)

Dribbbleの https://dribbble.com/shots?list=animated のひとつだけランダム表示する、**gifアニメランダム表示アプリ**

###  必要なもの

1. gifを一つ取ってくる処理
1. 取ってきたものを表示させる処理
1. レイアウト・装飾
1. チェンジボタン（他にはなにも用意しない）
1. ボタンは唯一それだけなので可愛いアクションにしたい、ので、それに必要なもの（js?css?）

### 補足

- 学習におすすめの日本語記事：ないらしいので定期Electron勉強会で聞く

**Comment by putchom** [comment]
:eyes:

**Comment by dojineko** [comment]
:eyes:

**Comment by keitakawamoto** [comment]
http://developer.dribbble.com/

**Comment by keitakawamoto** [comment]
# 導入手順

※すぐに古くなるので気をつける

- nodebrew
- node.js
- npm （npmについて https://github.com/keitakawamoto/orangebomb.org/issues/17 ）

上記について多少なりとも知識を持っていた方が進めやすいと思われる。

1.[Homebrew](http://brew.sh/index_ja.html)（OS X 用パッケージマネージャー）を使ってnodebrewを入れる

```
brew update
brew install nodebrew
exec $SHELL # 設定読み直し
```

2.nodebrewを使ってnode.jsを入れる（nodeパッケージマネージャーであるnpmもセットで入る）

```
$ nodebrew ls-all
$ nodebrew install-binary v5.6.0
$ nodebrew use v5.6.0 use v5.6.0
$ node --version v5.6.0
$ npm --version 3.6.0
$ nodebrew ls
```

3.npmを使ってElectronを入れる

```
npm -g install electron-prebuilt
```

**Comment by keitakawamoto** [comment]
- [30分で出来る、JavaScript (Electron) でデスクトップアプリを作って配布するまで](http://qiita.com/nyanchu/items/15d514d9b9f87e5c0a29)

**Comment by keitakawamoto** [comment]
ディレクトリ作成する場面なので、名前を決めよう。
決まったらリポジトリも作成しそこにpushしていくことにする。

**Comment by keitakawamoto** [comment]
# Gif One

にアプリケーション名決定。

**Comment by keitakawamoto** [comment]
## リポジトリ作成

- https://github.com/keitakawamoto/gifone

作成した。作品ドリブンだ！！！！！！！！！

**Comment by keitakawamoto** [comment]
## npm init：package.json を生成した

```
$ npm init
```

上記コマンドでpackage.json を生成できる。
詳しくは

- https://github.com/keitakawamoto/orangebomb.org/issues/17#issuecomment-193384744
- https://github.com/keitakawamoto/orangebomb.org/issues/17#issuecomment-202350347

**Comment by keitakawamoto** [comment]
### `.json` とは

https://ja.wikipedia.org/wiki/JavaScript_Object_Notation より

**JSON（ジェイソン、JavaScript Object Notation）** は軽量なデータ記述言語の1つ。
構文はJavaScriptにおけるオブジェクトの表記法をベースとしているが、JSONはJavaScript専用のデータ形式では決してなく、様々なソフトウェアやプログラミング言語間におけるデータの受け渡しに使えるよう設計されている。

**Comment by keitakawamoto** [comment]
# Dribbble APIについて

世界の @taknakamu がすごいqiita記事を書いてくださった。感謝。

- [](Dribbble APIの使い方とランダムに画像とってくるやつの作り方)

これで自分の企画だけど80%ムタさん制作だな！（ﾊﾞｰﾝ）
`README.md` のクレジットにしっかり追加する。

**Comment by keitakawamoto** [comment]
## ムタさんが瞬殺

- http://codepen.io/nmtakay/pen/PNKxgL
 - リロードでランダム切り替え

完成しちゃってるよ！
もう俺がやることelectronでパッケージにすることしか残ってないよ！
くやしいから仕組みを完全理解するぞ！！！！

**Comment by keitakawamoto** [comment]
## index.html追加

- https://github.com/keitakawamoto/gifone/commit/759ffa3364e9f6fc3c2ad8410eda27313d6ceea0

**Comment by keitakawamoto** [comment]
## index.js 追加

- https://github.com/keitakawamoto/gifone/commit/0f03ddb81f824e3b52fb1ee6cccf2f0f3e15a8c6

http://qiita.com/nyanchu/items/15d514d9b9f87e5c0a29 をベースに @udzura が勉強会用に作成したものを調整して利用させていただいた。

**Comment by keitakawamoto** [comment]
## 起動

起動コマンド

```
$ electron .
```

![image](https://cloud.githubusercontent.com/assets/1661325/14425109/c1c71708-001f-11e6-9bcf-f1c9b043e0af.png)


構造

```
gifone
├── index.html
├── index.js
├── package.json
└── README.md
```


## ハマった部分

<img width="532" alt="2016-04-11 19 49 00" src="https://cloud.githubusercontent.com/assets/1661325/14425016/4c66326e-001f-11e6-80ff-23b4a5b82953.png">

package.json で指定しているファイル名と実際のファイル名が一致しなければ起動しない。

**Comment by keitakawamoto** [comment]
次は

- [アーカイブ化](http://qiita.com/nyanchu/items/15d514d9b9f87e5c0a29#%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E3%82%A2%E3%83%BC%E3%82%AB%E3%82%A4%E3%83%96%E5%8C%96%E3%81%99%E3%82%8B) （アーカイブ化とは？）
- [パッケージング](http://qiita.com/nyanchu/items/15d514d9b9f87e5c0a29#%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E9%85%8D%E5%B8%83%E3%81%99%E3%82%8B)

**Comment by keitakawamoto** [comment]
orangebomb.tips移行、移行後内容を削除
