### ISSUE TITLE
Adobe Premiere 入門

### ISSUE THREAD

**Issue by keitakawamoto** [keitakawamoto/orangebomb.org#36]
**AfterEffectは 映像素材作成ツール 、映像制作ツールは Adobe Premiere。** （https://github.com/keitakawamoto/orangebomb.org/issues/34#issuecomment-218524422 ）
映像制作をしたいので習得する。

以下 https://www.adobe.com/jp/products/premiere.html より

```
どこにいても、圧倒的な映像を制作
業界最高峰のビデオ制作ツールセットで、作業効率をさらにアップ。デスクトップとモバイルアプリから
クリエイティブアセットにいつでもアクセスできるので、どこにいても鮮やかな色彩あふれる
プロフェッショナルな映像作品を制作できます
```

**Comment by keitakawamoto** [comment]
## 開始

まずは `新規開始`

![image](https://cloud.githubusercontent.com/assets/1661325/15221737/aba1d1b6-18a7-11e6-8e11-165611378502.png)

ファイルの新規作成。 ※Premiereのファイルの拡張子は `.prproj`

![image](https://cloud.githubusercontent.com/assets/1661325/15221758/ba4ee82a-18a7-11e6-97db-9666211411aa.png)

### まずやることは新規シーケンス作成

`ファイル` > `新規` > `シーケンス`

![image](https://cloud.githubusercontent.com/assets/1661325/15222005/c5a9de40-18a8-11e6-8bed-a99e4476f30b.png)

以下 http://dictionary.goo.ne.jp/jn/92991/meaning/m0u/ より。

```
シーケンス【sequence】

《「シークエンス」とも》
１ 連続。連続して起こる順序。
２ 映画やテレビで、一続きのシーンによって構成される、ストーリー展開上の一つのまとまり。「六シーン二三カットの―」
３ 機器を自動制御する際の、あらかじめ設定しておく動作の順序。
４ カリキュラム編成において、教科内容の段階的学習の順序。→スコープ
５ トランプで、数が連続する同種の3枚以上のカード。

シーケンスチェック【sequence check】
コンピューターで、データ入力の間違いを検査するため、データを入力するときに、事前に定められた順序に従って入力されているか否かを調べること。

シーケンスロボット
《(和)sequence＋robot》単純繰り返しロボット。動作順序（シーケンス）を設定されると、それにより定まった動作のみを行う自動機械。固定シーケンス式と可変シーケンス式がある。欧米ではこれをロボットとみなさない。
```

詳細設定

- [ ] 各項目の詳細について調べる

![image](https://cloud.githubusercontent.com/assets/1661325/15222132/3ca2fcd4-18a9-11e6-891f-1390c7ebdc58.png)

![image](https://cloud.githubusercontent.com/assets/1661325/15222229/9833c8bc-18a9-11e6-81c9-b9848adafe95.png)

![image](https://cloud.githubusercontent.com/assets/1661325/15222235/9dddbf70-18a9-11e6-8857-af558cbef910.png)

http://premiere101.net/jp/b01.html より、自動シーケンス設定について。

> これは動画サイズなどの形式を指定するものですが、種類がありすぎて全く分からないと思います。
心配しなくて大丈夫です。うれしいことにAdobe Premiere Pro CS6からは、読み込んだ動画によって自動でシーケンスを設定してくれるようになったので、ひとまずここは何を選んでも大丈夫です。

これで作業開始地点に立った。

![image](https://cloud.githubusercontent.com/assets/1661325/15222251/af997d9e-18a9-11e6-8cfe-b4c51b9ccec7.png)

**Comment by keitakawamoto** [comment]
## 素材の読み込み

`ファイル` > `読み込み` で可能。
`プロジェクトパネル` に追加される。
プロジェクトパネルにドラッグ&ドロップしてもOK。

![image](https://cloud.githubusercontent.com/assets/1661325/15222420/8be7b55e-18aa-11e6-88ad-75fea9a5b001.png)

**Comment by keitakawamoto** [comment]
## 素材の編集

まずは素材をシークエンス上に配置（ドラッグ&ドロップ）

![image](https://cloud.githubusercontent.com/assets/1661325/15222624/8f6d1a38-18ab-11e6-81d2-7f51913cb936.png)

`レーザーツール` を使えば動画（クリップ）を分割できる。

![image](https://cloud.githubusercontent.com/assets/1661325/15223181/14602ada-18ae-11e6-8b10-a392fb0967e3.png)

![image](https://cloud.githubusercontent.com/assets/1661325/15223215/39fef46a-18ae-11e6-8d7d-54b553fdee0e.png)

`選択ツール` でいらない部分を選び `derete` キーで削除できる。

![image](https://cloud.githubusercontent.com/assets/1661325/15223232/4e5e0734-18ae-11e6-8e12-35c09834ffb1.png)

![image](https://cloud.githubusercontent.com/assets/1661325/15223248/689e0a0e-18ae-11e6-921f-f756ce34d0f0.png)

## 素材の列について

２列あるのは、 `映像` と `音声` の模様。
デフォルトプレビューでは音が流れないようなので確認する。

![image](https://cloud.githubusercontent.com/assets/1661325/15223290/a410469c-18ae-11e6-8665-82e8328b60c0.png)

**Comment by keitakawamoto** [comment]
## プレビュー

~~プレビューパネル~~ プログラムパネルのプレビュー部分で操作できる。

![image](https://cloud.githubusercontent.com/assets/1661325/15223458/88be30ec-18af-11e6-908b-db5120346652.png)

**Comment by keitakawamoto** [comment]
## ソース

素材をダブルクリックすると、ソースパネルに表示される。
ここで素材そのものを再生・確認することができる。

![image](https://cloud.githubusercontent.com/assets/1661325/15251208/43731282-1963-11e6-8b98-4fae58440c67.png)

**Comment by keitakawamoto** [comment]
## レイヤーとエフェクト

レイヤーを分け、動画を重ねることで、透明度0から100へ変化するフェードインエフェクトが表現できる。
素材をダブルクリックし、 `エフェクトコントロールパネル` から様々なエフェクトを実装できる。
Photoshopのレイヤースタイルと同じ感覚で利用できる。
エフェクトの開始・終了位置の調整はAfterEffectの https://github.com/keitakawamoto/orangebomb.org/issues/8#issuecomment-216676487 と同じように操作。

![image](https://cloud.githubusercontent.com/assets/1661325/15252045/21a3dafc-1967-11e6-864f-19f6767ff118.png)

**Comment by keitakawamoto** [comment]
## 素材をフレームのサイズに合わせてスケールする

シーケンス上の該当の動画の部分で二本指でタップ（右クリック） > `フレームサイズに合わせる` でフィットさせることができる。素材の縦横の比率は固定。

![image](https://cloud.githubusercontent.com/assets/1661325/15265166/19a2fb10-19b9-11e6-9bfa-098f4553caa3.png)

**Comment by keitakawamoto** [comment]
## エフェクトパネル

エフェクトコントロールとは違い、既存のエフェクトをすぐに利用出来るもの。
いろいろなエフェクトが揃っている。場面の切り替わりを一瞬重ねて透明度を上げていくエフェクトも https://github.com/keitakawamoto/orangebomb.org/issues/36#issuecomment-219075111 のように自分で作らなくてもすぐに適用させることができる。調整したい場合は、エフェクトコントロールを使うといいかもしれない。

![image](https://cloud.githubusercontent.com/assets/1661325/15265284/50790178-19bb-11e6-817e-b13271d21f74.png)

**Comment by keitakawamoto** [comment]
## 文字を入れる

プロジェクトの新規項目で `タイトル` を選択。

![image](https://cloud.githubusercontent.com/assets/1661325/15265566/bd36003e-19c2-11e6-8baa-452d4b35114d.png)
![image](https://cloud.githubusercontent.com/assets/1661325/15265567/ccaaccde-19c2-11e6-956f-1626bb52c616.png)
![image](https://cloud.githubusercontent.com/assets/1661325/15265571/dc10275a-19c2-11e6-8f02-87d9b5134d80.png)

Photoshop感覚で内容を入力・フォント指定等行う。

![image](https://cloud.githubusercontent.com/assets/1661325/15265587/2f534b54-19c3-11e6-97c3-461153029fbf.png)

素材としてシーケンスの中にドラッグ&ドロップし実装できる。

![image](https://cloud.githubusercontent.com/assets/1661325/15265600/6c68e864-19c3-11e6-8599-db9bd1b4971d.png)

**Comment by keitakawamoto** [comment]
## 音楽を重ねる

音の素材をシーケンスの音声側にドラッグ&ドロップで配置できる。


![image](https://cloud.githubusercontent.com/assets/1661325/15265638/e6644c5c-19c4-11e6-9582-f1de30c695a2.png)

オーディオクリップミキサーパネルに、シーケンス内の音声レイヤー分のボリュームが表示されるので、調節が可能。

![image](https://cloud.githubusercontent.com/assets/1661325/15265653/5a5cf1ae-19c5-11e6-8d43-aa4ac002cf83.png)

## 音楽の部分的な音量調節

レイヤーの縦幅を広げる。

![image](https://cloud.githubusercontent.com/assets/1661325/15265692/97eda792-19c6-11e6-8f96-64b3f7191a99.png)

音量調節したい場面で、`キーフレームの書き込み` をクリック。
その後、プレビューを行い、音量をつまみを調節して変更する。

![image](https://cloud.githubusercontent.com/assets/1661325/15265777/4b1a3432-19c9-11e6-8f73-bacc486f1c8a.png)

つまみを使った音量調節が記録され、保存される。

![image](https://cloud.githubusercontent.com/assets/1661325/15265791/adab58a6-19c9-11e6-94ca-f7209f6d81b1.png)

**Comment by keitakawamoto** [comment]
## 書き出し

![image](https://cloud.githubusercontent.com/assets/1661325/15309677/fce2077e-1c23-11e6-803c-0d97823f95fb.png)

**シーケンスをアクティブにしてから** `ファイル` > `書き出し` > `メディア` と進む。

![image](https://cloud.githubusercontent.com/assets/1661325/15309718/468debc2-1c24-11e6-823e-e541e9258614.png)

書き出し設定ダイアログで `形式` や `品質` などの設定ができる。
そのまま書き出す場合 `書き出し` 、エンコードする場合 `キューに追加` へ進む。

キューへ進むと、 エンコーダーが起動し、エンコードを開始できる。

![image](https://cloud.githubusercontent.com/assets/1661325/15309758/8b4503ea-1c24-11e6-9c65-820a3c92cd4b.png)

## DVDに焼くには

Premiereから書き出したデータを、 **DVDオーサリングソフトを使って焼く。**
Premiereで焼くのではない。
オーサリングソフトはいろいろあるのでケースによって最適なものを見つけると良い。
ソフトによって、Premiereで書き出すべき形式も変わる。

**Comment by keitakawamoto** [comment]
レンダリングやエンコードに関しては https://github.com/keitakawamoto/orangebomb.org/issues/37 で深める。

**Comment by keitakawamoto** [comment]
## シン・ゴジラの編集ソフトとして採用された

- http://japan.cnet.com/interview/35088333/2/

![2016-09-05 14 43 37](https://cloud.githubusercontent.com/assets/1661325/18300733/f1aa627a-7506-11e6-97f4-d46c2843e9b0.png)

**Comment by keitakawamoto** [comment]
## AfterEffectのように位置移動させる

[Premiere Pro でエンドロールクレジットを作成する](http://jmplanning.net/premire/207.html)より

`エフェクトコントロール` でキーフレームが扱えるので、AfterEffectのように位置移動させることができる。

![1](https://cloud.githubusercontent.com/assets/1661325/23382267/dd17cb70-fd84-11e6-953e-b33c98bc51b9.png)

**Comment by keitakawamoto** [comment]
夢の映画のようなエンドロールが作れて俺は満足じゃよ....
観察の末に得た知見は、文字は真っ白ではなく、少しだけ青みを持たせるとかなりそれっぽくなる

**Comment by keitakawamoto** [comment]
## 音声をフェードイン、フェードアウトさせる方法

- [Premiere Pro CCで音声をフェードイン、フェードアウトさせる方法【初心者向】](https://infinityakira-wp.com/tool/premiere-pro-cc-fadeinout/)

`エフェクト` の `オーディオトランジション` の `クロスフェード` の `指数フェード` 挿入でできる。

![image](https://cloud.githubusercontent.com/assets/1661325/23830181/dbc6718c-0747-11e7-8f3f-5c750ca38b72.png)

**Comment by YamatoNagata** [comment]
ああー、俺もこんなん作りたい

**Comment by keitakawamoto** [comment]
@YamatoNagata premiereやりましょう最高ですよ。夢だったことが実現できるレベルです

**Comment by keitakawamoto** [comment]
## 書き出し：形式はH.264

- `ファイル` > `書き出し` > `メディア`

![image](https://cloud.githubusercontent.com/assets/1661325/23964888/6f3e0eb2-09f9-11e7-8d08-f0c65aea3d46.png)

形式を `H.264` にすることで、見たことのあるプリセットが見えてくる。

![image](https://cloud.githubusercontent.com/assets/1661325/23964920/8caccc18-09f9-11e7-8c87-cd14ad892212.png)

## ソースの一致 - 高速ビットレート を選択

ソースの一致、これは元動画と同じ画角、同じフレームレートということ。
特に設定せずキューを追加で良い。 あとは https://github.com/keitakawamoto/orangebomb.org/issues/36#issuecomment-219605747 と同じ。

**Comment by keitakawamoto** [comment]
## 2017.04 アップデートに関する瀬戸弘司氏によるチュートリアル

- [Premiere Pro 大型アップデート紹介 第一回「テロップ編」](https://www.youtube.com/watch?v=mwfB8vq6GbU&feature=youtu.be)
- [Premiere Pro 大型アップデート紹介 第二回「オーディオ編」](https://www.youtube.com/watch?v=mam4jovmijI&feature=youtu.be)

**Comment by keitakawamoto** [comment]
## 部分的にぼかしをかける

エフェクトコントロール -> ブラー（ガウス）

![image](https://user-images.githubusercontent.com/1661325/37617702-3ce79f52-2bf7-11e8-85c5-48fc46dadd38.png)

開始位置にキーフレームを打つ

![image](https://user-images.githubusercontent.com/1661325/37617736-5a5de74e-2bf7-11e8-85c3-8e18278e33b0.png)

図形をクリックし、マスクを追加。追加した分だけ「マスク」という名前が追加される。
キャプチャは３つ目。１、２個目は削除済み。

![image](https://user-images.githubusercontent.com/1661325/37624639-26f4a018-2c0c-11e8-9ac4-8bc4c92729e6.png)

「マスクパス」をアクティブにし、位置を調整していく。これで画面が動いてもぼかしを適切な位置に配置できる。

![image](https://user-images.githubusercontent.com/1661325/37625209-5bca8fb2-2c0e-11e8-9e98-3229d9c68259.png)

**Comment by YamatoNagata** [comment]
素材ファイルサイズどれくらい？

**Comment by keitakawamoto** [comment]
@YamatoNagata  撮影した動画のファイルサイズ×個数分です。aftereffectで編集した素材も含む場合それも込みになります。
